version: '3'
services:
    py-srv:
        build: py-srv
        ports:
        - 80:6543
        depends_on:
        - db
        links:
        - db:db
    py-test-srv:
        build:
            context: py-test-srv
        command: sh -c "/wait && python app.py"
        environment:
        - WAIT_HOSTS=db:3306,py-srv:6543
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
        depends_on:
        - py-srv
        links:
        - py-srv:py-srv
    db:
        image: dolthub/dolt-sql-server
        ports:
        - 3306
        healthcheck:
            test: exit 0
        volumes:
        - ./db/sql:/docker-entrypoint-initdb.d
